### ISSUE TITLE
Spinning loader after stopping recording in firefox

### ISSUE THREAD

**Issue by ajmyers01** [Ziggeo/ziggeo-client-sdk#33] opened 2020-02-18 23:32 UTC
I have an implementation of the Ziggeo Javascript SDK.
The recorder loads and lets me hit record and start recording a video, when I hit stop, it just sits and spins with no option to do anything on the screen. 

Console error thrown: 
```
TypeError: this.__mediaRecorderOptions.mimeType is undefined ziggeo.js:7:284312 
```

This is a new bug that popped up we tested the original implementation 6 months ago or so and it worked fine. 
We have also tested that our implementation works in Chrome and IE. 

This is affecting our production build. Please advise. 

## Versions
Firefox 73.0.1(64 bit) 
Ziggeo v1-stable

**Comment by ntshcalleia** [comment] 2020-02-19 00:55
Hi Alex, I think this may be related to #30, which was caused by [a recent Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1594466). It was fixed on r34, so please try upgrading to that version and let us know if it helps.

**Comment by ajmyers01** [comment] 2020-02-19 05:42
Upgrading to r34 worked, When will stable be updated to match r34 or r35 ?

**Comment by Bane-D** [comment] 2020-02-19 16:30
Hi Alex,

Natasha passed the info to our team and the stable revision got hot fixed.

If you change back to stable at this point it should work fine.

Please do just remember that caching can be happening especially since it is a very small change, so you can always add _?ver=123_ to the end of the URL for ziggeo.js file.

* It can be anything that you add, just so that browsers know it is a new version.

**Closed as completed** 2020-02-19 18:44 UTC
