### ISSUE TITLE
Video upload failing on Safari 13.1 about half the time.

### ISSUE THREAD

**Issue by dpretty** [Ziggeo/ziggeo-client-sdk#37] opened 2020-04-29 21:58 UTC
We noticed on our server that video uploads were sometimes failing when using Safari. A user would record a video and eventually see "Verifying failed - click here to retry". Clicking to retry the verification would always result in another failure.

I can reproduce with a simple test case, running the following locally on my computer (using `python -m http.server 8001` to serve file locally, and replacing the token with a valid one)

```html
<html>
<head>
    <link rel="stylesheet" href="https://assets.ziggeo.com/v2-stable/ziggeo.css"/>
    <script src="https://assets.ziggeo.com/v2-stable/ziggeo.js"></script>
    <script>
      var ziggeoApp = new ZiggeoApi.V2.Application({
        token: 'xxx',
        webrtc_streaming_if_necessary: true,
        webrtc_on_mobile: true
      })
    </script>
</head>
<body>
<h1>TEST ZIGGEO JS</h1>
<div id="replace_me-v2_recorder" style="width: 100%"></div>
<script>
  ziggeoApp.on('ready', function () {
    var recorder = new ZiggeoApi.V2.Recorder({
      element: document.getElementById('replace_me-v2_recorder'),
      attrs: {
        height: 400,
      }
    })
    recorder.activate()
  })
</script>
</body>
</html>
```

The video upload/verification works sometimes, and fails sometimes - I'd guess about 50% success rate

During the a failing verify process, ziggeo js is polling (with HTTP POST)
`/v1/applications/xxx/videos/xxx/streams/xxx/recordersubmit`

and always getting a response:

```json
{
    "status": 412,
    "responseText": "Could not read video file"
}
```

I've been testing with Safari 13.1 on macOS 10.15.4

Any ideas? Happy to provide more info if required.

**Comment by Bane-D** [comment] 2020-04-29 22:42
Hi Dave,

Can you please add `timeminlimit` parameter for 10 seconds or more.

For example (using your code):
```js
  ziggeoApp.on('ready', function () {
    var recorder = new ZiggeoApi.V2.Recorder({
      element: document.getElementById('replace_me-v2_recorder'),
      attrs: {
        height: 400,
        timeminlimit: 10
      }
    })
    recorder.activate()
  })
```

Once you do it will likely not fail any more at all. Of course please do let me know how it goes.

Regards,
Bane

**Comment by dpretty** [comment] 2020-04-29 23:25
Thanks @Bane-D, in my testing that appears to fix the issue.

We'd prefer not to impose a 10 second minimum on our users. I tried timeminlimit = 5 and that also seemed to fix the issue for me.

Do you know if there's a reliable minimum value for timeminlimit which resolves this issue? Or does it depend on the environment (e.g. network bandwidth, latency) ?

Also, is this an issue which Ziggeo will be able to resolve in a future release (i.e. fix the issue without requiring timeminlimit)? Or are there constraints imposed by Safari which causes this issue?

Thanks!

**Comment by Bane-D** [comment] 2020-04-30 01:20
Great to hear that it working for you Dave.

The cause is actually made by the type of the WebRTC implementation available on Safari. They only have WebRTC Streaming implementation. This means that we need to take into account the time for different servers to sync the data before we actually are able to have recording.

This takes random time and depends on different things mostly latency. This is why I suggested 10 seconds because during this time you can be sure that all servers will sync together and data will actually be captured.

Now for you or anyone not sure why I say servers and sync - just a quick overview of streaming >> Every time the streaming is done (same is with Skype and others like it, including our system) what happens is that there are many servers being contacted in same time. That way your device sends different parts of data to different servers.

This might seem strange however this is how it is possible for streaming to work fast. Now during this initial phase it will take few seconds to detect where all of these servers have a marker that they can agree upon as positive marker.

Later, once all of the data is collected to be made into single video, these markers are searched for and then combined to give you the actual video.

Example:
Some part on server A might be 0.4s before the other server B, and a third server C could be 1.2 seconds after all other). Imagine this all be put into a 0 point that is find on all (union of A,B,C) and all starts from there.
This means dropping the 1.6 seconds that the first server A had and 1.2 seconds from the second B, making it all synced up properly between [ABC].

So for the streaming, I would suggest some time, 5 seconds very minimal amount however 10 seconds being best to be safe for all those different network cases.

It will not be needed for non Safari browsers that use standard WebRTC, you can remove minimal time limit for such recordings.

Hope this helps.

**Comment by rjchaveiro** [comment] 2020-07-28 22:19
Having the same issue for safari, with the exception that it doesn't even seem to be triggering a POST a request at all.
For the following:

```JS
this.ziggeoApp = new ZiggeoApi.V2.Application({
  token: ZIGGEO_API_KEY,
  webrtc_streaming_if_necessary: true,
  webrtc_on_mobile: true
});

[...]
this.ziggeoApp.on('ready', function() {
  self.ziggeoApp.ready = true;
   var recorderOptions = {
    timelimit: 300,
    timeminlimit: 30,
    stretch: true,
    height: 240,
    width: 360,
    theme: 'modern',
    allowcustomupload: false,
    allowupload: false,
  };

  this.recorder = new ZiggeoApi.V2.Recorder({
   element: element,
   attrs: recorderOptions
  });
});
```

It works well for other browsers.

Side note. seems like that 
```
  timelimit: 300,
  timeminlimit: 30,
```
Doesn't seem to work on mobile Safari. As currently able to record videos with a duration lower than 30s

**Comment by Bane-D** [comment] 2020-07-29 22:43
Hi Rodrigo,

I think this might look similar, however does seem to be different based on what you mentioned. Can you please open up a new issue for this or reach out to us over support@ziggeo.com?

Fine to come back here and link to it (if you open the issue) so it is easy for others to find, however since it is different we might need a bit of back and forth first.

Regards,
Bane

**Comment by rjchaveiro** [comment] 2020-07-30 16:56
Hey @Bane-D,

Moved into another issue here #40

**Comment by Bane-D** [comment] 2020-07-30 22:32
Great, thank you Rodrigo.

* Will also close this one at this time

Best,
Bane

**Closed as completed by Bane-D** 2020-07-30 22:32 UTC
